name = Sword
description = Fluid layout.
preview = preview.png
template = sword-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation
regions[header]         = Header
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[link]           = Link
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/sword/sword.layout.css
stylesheets[all][] = css/layouts/sword/sword.layout.no-query.css
