<?php

/**
 * Implements hook_block_info().
 */
function searchbox_block_info() {
	$blocks = array();
	$blocks = array(
		'block_chaoxing_discovery' => array(
			'info' => t('检索：超星发现检索'),
		),
		'block_duxiu_search' => array(
			'info' => t('检索：读秀统一检索'),
		),
		'block_book_search' => array(
			'info' => t('检索：馆藏书刊检索'),
		),
		'block_database_search' => array(
			'info' => t('检索：数据库检索'),
		),
		'block_ancient_search' => array(
			'info' => t('检索：古籍书目检索'),
		),
		'block_open_search' => array(
			'info' => t('检索：开放资源检索'),
		),
		'block_user_login' => array(
			'info' => t('登录：我的图书馆'),
		),
	);

	return $blocks;
}

/**
 * Implements hook_block_view().
 */
function searchbox_block_view($delta = '') {
	$block = array();

	switch ($delta) {
		case 'block_chaoxing_discovery':
			$block['subject'] = t('超星发现检索');
			$block['content'] = _searchbox_block_chaoxing_discovery();
			break;

		case 'block_duxiu_search':
			$block['subject'] = t('读秀统一检索');
			$block['content'] = _searchbox_block_duxiu_search();
			break;

		case 'block_book_search':
			$block['subject'] = t('馆藏书刊检索');
			$block['content'] = _searchbox_block_book_search();
			break;

		case 'block_database_search':
			$block['subject'] = t('数据库检索');
			$block['content'] = _searchbox_block_database_search();
			break;

		case 'block_ancient_search':
			$block['subject'] = t('古籍书目检索');
			$block['content'] = _searchbox_block_ancient_search();
			break;

		case 'block_open_search':
			$block['subject'] = t('开放资源检索');
			$block['content'] = _searchbox_block_open_search();
			break;

		case 'block_user_login':
			$block['subject'] = t('登录我的图书馆');
			$block['content'] = _searchbox_block_user_login();
			break;
	}

	return $block;
}

function _searchbox_block_chaoxing_discovery() {
	$html = <<<'HTML'
	<form role="form" action="http://ss.zhizhen.com/s">
		<div class="search-form-box">
			<input type="text" name="sw" id="swtext" placeholder="请输入关键词&hellip;"><input type="submit" value="检索"/>
			<input type="hidden" name="enc" value="utf-8" />
			<div class="intro">搜索1348家图书馆的资料文献，为教育科研提供专业服务</div>
		</div>
	</form>
HTML;

	return $html;
}

function _searchbox_block_duxiu_search() {
	$html = <<< 'HTML'
	<form action="http://www.duxiu.com/gosearch.jsp" method="post">
		<div class="search-form-box">
			<div class="radio"><input type="radio" name="channel" value="goqw.jsp " checked="checked" > 知识</div>
			<div class="radio"><input type="radio" name="channel" value="search" > 图书</div>
			<div class="radio"><input type="radio" name="channel" value="searchJour" > 期刊</div>
			<div class="radio"><input type="radio" name="channel" value="searchThesis" >学位论文</div>
			<div class="radio"><input type="radio" name="channel" value="searchCP" > 会议论文</div>
			<div class="radio"><input type="radio" name="channel" value="searchStd" > 标准</div>
			<div class="radio"><input type="radio" name="channel" value="searchPatent" > 专利</div>
			<div class="radio"><input type="radio" name="channel" value="searchVideo" > 视频</div>
			<div class="radio"><input type="radio" name="channel" value="searchInfo" > 信息资讯</div>
			<input id="sw" name="sw" id="sw" type="text" placeholder="请输入关键词进行检索&hellip;"><input type="submit" value="检索" name="submit"> 
			<input type="hidden" value="utf-8" name="enc" />
			<div class="intro">
				<ul>
					<li><a href="http://book.duxiu.com/advsearch.jsp">高级检索</a></li>
					<li><a href="http://www.duxiu.com/help/help.html">使用帮助</a></li>
				</ul>
			</div>
		</div>
	</form>
HTML;

	return $html;
}

function _searchbox_block_book_search() {
	$html = <<< 'HTML'
	<form action="http://opac.gxnu.edu.cn/opac/openlink.php" method="get" name="f" id="f">
		<div class="search-form-box">
			<!--
			<select class="option" name="strSearchType">
	            <option value="title">题名</option>
	            <option value="author">责任者</option>
	            <option value="keyword">主题词</option>
	            <option value="isbn">ISBN/ISSN</option>
	            <option value="asordno">订购号</option>
	            <option value="coden">分类号</option>
	            <option value="callno">索书号</option>
	            <option value="publisher">出版社</option>
	            <option value="series">丛书名</option>
	            <option value="tpinyin">题名拼音</option>
	            <option value="apinyin">责任者拼音</option>
	        </select>
			<select class="option" name="match_flag">
	            <option value="forward">前方一致</option>
	            <option value="full">完全匹配</option>
	            <option value="any">任意匹配</option>
	        </select>
			<br>
			<div class="radio">
				<input type="radio" name="doctype" value="all" checked="checked" /> 所有书刊
			</div>
			<div class="radio">
			    <input type="radio" name="doctype" value="01" /> 中文书
			</div>
			<div class="radio">
			    <input type="radio" name="doctype" value="02" /> 西文书
			</div>
			<div class="radio">
			    <input type="radio" name="doctype" value="11" /> 中文刊
			</div>
			<div class="radio">
			    <input type="radio" name="doctype" value="12" /> 西文刊
			</div>
			<br/>
			-->
			<input type="hidden" id="strSearchType" name="strSearchType" value="title">
			<input type="hidden" id="match_flag" name="match_flag" value="forward">
			<input type="hidden" id="doctype" name="doctype" value="ALL">
			<input type="hidden" id="with_ebook" name="with_ebook" value="on">
			<input type="hidden" id="displaypg" name="displaypg" value="20">
			<input type="hidden" id="showmode" name="showmode" value="list">
			<input type="hidden" id="sort" name="sort" value="CATA_DATE">
			<input type="hidden" id="orderby" name="orderby" value="desc">
			<input type="hidden" id="dept" name="dept" value="ALL">
			<input type="hidden" id="historyCount" name="historyCount" value="1" />
			<input type="text" name="strText" id="strText" placeholder="请输入书名检索馆藏书刊&hellip;" /><input type="submit" value="检索"/>
			<div class="intro">
			<ul>
				<li><a href="http://opac.gxnu.edu.cn/reader/login.php">借阅信息</a></li>
				<li><a href="node/35">预约续借</a></li>
				<li><a href="http://opac.gxnu.edu.cn/top/top_lend.php">热门借阅</a></li>
				<li><a href="http://opac.gxnu.edu.cn/newbook/newbook_cls_browse.php">新书通报</a></li>
				<li><a href="http://opac.gxnu.edu.cn/asord/asord_hist.php">读者荐购</a></li>
			</ul>
			</div>
		</div>
	</form>
HTML;

	return $html;
}

function _searchbox_block_database_search() {
	$html = <<< 'HTML'
	<form id="dbsearch" accept-charset="utf-8" method="get" action="/dbnav">
		<div class="search-form-box">
			<input id="edit-keys" name="keys" type="text" placeholder="请输入数据库名称进行检索&hellip;"><input id="edit-submit-clone-of-dbnav" type="submit" value="检索">
			<div class="intro">
				<ul>
					<li><a href="/dbnav">数据库导航</a></li>
					<li><a href="/res_journal">电子期刊</a></li>
					<li><a href="/res_ebook">电子图书</a></li>
					<li><a href="/res_demo">试用资源</a></li>
					<li><a href="/res_multimedia">多媒体资源</a></li>
				</ul>
				<ul>
					<li><strong><span style="color: #922525">常用数据库：</span></strong></li>
					<li><a href="http://www.cnki.net">CNKI</a></li>
					<li><a href="http://qikan.cqvip.com/">维普</a></li>
					<li><a href="http://www.duxiu.com/">读秀学术搜索</a></li>
					<li><a href="http://www.sciencedirect.com/">Elsevier SD</a></li>
					<li><a href="http://onlinelibrary.wiley.com/">Wiley Blackwell</a></li>
					<li><a href="http://link.springer.com/">Springer</a></li>
					<li><a href="http://search.ebscohost.com/">EBSCO</a></li>
					<li><a href="http://www.tandfonline.com/">Taylor & Francis</a></li>
				</ul>
			</div>
		</div>
	</form>
HTML;

	return $html;
}

function _searchbox_block_ancient_search() {
	$html = <<< 'HTML'
	<form id="searchForm" accept-charset="utf-8" method="post" action="http://202.193.168.18:1128/search/">
		<div class="search-form-box">
			<!--
			<select id="type" name="type">
				<option value="題名" selected="selected">書名</option>
				<option value="責任說明">作者</option>
				<option value="關鍵字">關鍵字</option>
			</select>
			-->
			<input id="keyword" name="keyword" type="text" placeholder="请输入古籍書目进行檢索&hellip;"><input id="search" name="search" type="submit" value="檢索">
			<div class="intro">
                <ol>
                    <li>系統提供本館所藏古籍書名、著者、著作方式、版本項、函數、卷/冊數、存卷/冊數、部/套數、四部分類號、附注以及索書號、財產號等基本資訊。</li>
                    <li>系統依據原卡片目錄繁體字著錄，讀者查詢時使用繁體字檢索。</li>
                </ol>
			</div>
		</div>
	</form>
HTML;

	return $html;
}

function _searchbox_block_open_search() {
	$html = <<< 'HTML'
	<form role="form" action="#" onsubmit="return false;">
		<div class="search-form-box">
			<div class="radio">
				<input type="radio" name="openbook" value="0"  title="Open Library，百万册免费电子书" checked="checked">
				<a  href="http://openlibrary.org/" target="_blank" title="Open Library，百万册免费电子书"> 开放图书馆</a>
			</div>
			<div class="radio">
				<input type="radio" name="openbook" value="1" title="6000种期刊+5000个开放获取数据库">
				<a target="_blank" href="http://www.souoa.com" title="6000种期刊+5000个开放获取数据库"> OA图书馆</a>
			</div>
			<div class="radio">
				<input type="radio" name="openbook" value="2"  title="近8千种开放获取期刊">
				<a target="_blank" href="http://www.doaj.org/" title="近8千种开放获取期刊"> DOAJ</a>
			</div>
			<div class="radio">
				<input type="radio" name="openbook" value="3" title="1700余种OA期刊论文">
				<a target="_blank" href="http://gooa.las.ac.cn/external/index.jsp" title="1700余种OA期刊论文"> GoOA</a>
			</div>
			<input type="text" name="q" placeholder="请输入关键词&hellip;"><input type="submit" value="检索" class="open_submit"/>
			<div class="intro">
				<ul>
					<li><a href="http://www.nlc.gov.cn/dsb_zyyfw/gj/gjzyk/" target="_blank">国图特色资源</a></li>
					<li><a target="_blank" href="http://or.nsfc.gov.cn/">国家自然科学基金基础研究知识库</a></li>
					<li><a href="http://www.gutenberg.org/" target="_blank">古腾堡计划</a></li>
					<li><a target="_blank" href="http://www.nssd.org/">国家哲学社会科学学术期刊数据库</a></li>
				</ul>
			</div>
		</div>
	</form>
HTML;

	return $html;
}

function _searchbox_block_user_login() {
	$html = <<< 'HTML'
	<form action="http://opac.gxnu.edu.cn/reader/redr_verify.php" name="frm_login" method="POST">
		<div class="search-form-box">
			<div class="input-text">
				<label for="number">证件号</label>
				<input id="number" name="number" type="text" size="20" style="width:150px" placeholder="证件号" >
			</div>
			<div class="input-text">
				<label for="passwd">密&nbsp;&nbsp;码</label>
				<input class="input" name="passwd" type="password" size="20" style="width:150px" placeholder="密码" >
			</div>
			<div class="input-text">
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<label for="captcha">验证码</label>
				<input id="captcha" name="captcha" type="text" size="20" style="width:150px" placeholder="输入4位数字验证码">
				<span id="captcha_tips" >
		            <a href="#">
		            	<img title="点击刷新" src="http://opac.gxnu.edu.cn/reader/captcha.php" align="absbottom" onclick="this.src='http://opac.gxnu.edu.cn/reader/captcha.php?'+Math.random();"></img>
		            </a>
		        </span>
	        </div>
	        <input type="hidden" name="select" value="cert_no">
	        <input type="submit" value="登录"/>
        </div>
    </form>
HTML;

	return $html;
}