name = Sword Front
description = Fluid layout.
preview = preview.png
template = sword-front-layout

; Regions
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[search_tab] = Search Tab
regions[showcase] = Showcase
regions[sidebar_first] = First sidebar
regions[sidebar_second] = Second sidebar
regions[link] = Link
regions[footer] = Footer

; Stylesheets
stylesheets[all][] = css/layouts/sword-front/sword-front.layout.css
stylesheets[all][] = css/layouts/sword-front/sword-front.layout.no-query.css
