name = Sword Front
description = Fluid layout.
preview = preview.png
template = sword-front-layout

; Regions
regions[bar] = Bar
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[search_tab] = Search Tab
regions[showcase] = Showcase
regions[postscript_first] = Postscript First
regions[postscript_second] = Postscript Second
regions[postscript_third] = Postscript Third
regions[postscript_fourth] = Postscript Fourth
regions[express] = Express
regions[link] = Link
regions[footer] = Footer

; Stylesheets
stylesheets[all][] = css/layouts/sword-front/sword-front.layout.css
stylesheets[all][] = css/layouts/sword-front/sword-front.layout.no-query.css
