name = Sword Front
description = Fluid layout.
preview = preview.png
template = sword-front-layout

; Regions
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[search_tab] = Search Tab
regions[stacked_first] = Stacked First
regions[stacked_second] = Stacked Second
regions[stacked_third] = Stacked Third
regions[link] = Link
regions[footer] = Footer

; Stylesheets
stylesheets[all][] = css/layouts/sword-front/sword-front.layout.css
stylesheets[all][] = css/layouts/sword-front/sword-front.layout.no-query.css
