<?php

/**
 * @file
 * Install file for the transliteration title module.
 */

/**
 * Implements hook_field_schema().
 */ 
function transliteration_title_field_schema($field) {
  return array(
    'columns' => array(
      'value' => array(
        'type' => 'varchar',
        'length' => 255,
        'not null' => FALSE,
        'sortable' => TRUE,
      ),
      'manual' => array(
        'type' => 'int',
				'not null' => TRUE,
        'default' => 0,
      ),
    ),
  );
}