name = Stair
description = Fluid layout.
preview = preview.png
template = stair-layout

; Regions
regions[bar] = Bar
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[search]           = Search Tab
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[showcase]  = Showcase
regions[sidebar_first] = First sidebar
regions[sidebar_second] = Second sidebar
regions[express] = Express
regions[link] = Link
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/stair/stair.layout.css
stylesheets[all][] = css/layouts/stair/stair.layout.no-query.css
