name = Stair
description = Fluid layout.
preview = preview.png
template = stair-layout

; Regions
regions[bar] = Bar
regions[branding] = Branding
regions[header] = Header
regions[navigation] = Navigation
regions[highlighted] = Highlighted
regions[help] = Help
regions[search_tab] = Search Tab
regions[showcase] = Showcase
regions[content] = Content
regions[sidebar_first] = First Sidebar
regions[sidebar_second] = Second Sidebar
regions[postscript_first] = Postscript First
regions[postscript_second] = Postscript Second
regions[postscript_third] = Postscript Third
regions[postscript_fourth] = Postscript Fourth
regions[express] = Express
regions[link] = Link
regions[footer] = Footer

; Stylesheets
stylesheets[all][] = css/layouts/stair/stair.layout.css
stylesheets[all][] = css/layouts/stair/stair.layout.no-query.css
